name: PHP CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Specify your desired PHP version
          extensions: mbstring, dom, fileinfo, pdo_mysql # Add any necessary extensions
       #   tools: composer # Install Composer

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
           server: ${{ secrets.SERVER }} 
           username: ${{ secrets.USERNAME }}
           password: ${{ secrets.PASSWORD }}
      # - name: Install Composer dependencies
      #  run: composer install --no-ansi --no-interaction --no-progress --prefer-dist

      # - name: Run tests
      #  run: vendor/bin/phpunit # Or your preferred testing command

      # Optional: Add steps for linting, code style checks, or deployment
      # - name: Run PHPStan
      #   run: vendor/bin/phpstan analyse

      # - name: Deploy to server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /var/www/your-app
      #       git pull
      #       composer install --no-dev
      #       php artisan migrate --force
